function controls = displayCzi(in)

    but_height = 0.1;
    controls.hfig = figure('Units', 'normalized', 'NumberTitle', 'off', ...
        'Name', in.filename);
    set(controls.hfig, 'Position', [0 0 1 0.95]);
    controls.hax = axes('Position', [0.25, 0.15, 0.5, 1-0.05-0.15]);
    controls.hzlbl = uicontrol('Style', 'text', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.2, 0.1, 0.05, 0.025], ...
        'HorizontalAlignment', 'right', ...
        'String', 'Z plane:');
    controls.hzsl = uicontrol('Style', 'slider', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.25, 0.1, 0.5, 0.025]);
    controls.hclbl = uicontrol('Style', 'text', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.2, 0.05, 0.05, 0.025], ...
        'HorizontalAlignment', 'right', ...
        'String', 'Channel:');
	controls.hcsl = uicontrol('Style', 'slider', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.25, 0.05, 0.5, 0.025]);
    controls.hsettopbut = uicontrol('Style', 'pushbutton', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - but_height, 0.15, but_height], ...
        'String', 'Set current Z plane as top of tissue');
    controls.hledgebut = uicontrol('Style', 'pushbutton', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - 2 * but_height, 0.15, but_height], ...
        'String', 'Take current edge as left basal surface');
    controls.hredgebut = uicontrol('Style', 'pushbutton', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - 3 * but_height, 0.15, but_height], ...
        'String', 'Take current edge as right basal surface');
    controls.hmidlbut = uicontrol('Style', 'pushbutton', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - 4 * but_height, 0.15, but_height], ...
        'String', 'Take current edge as midline');
    controls.hnextbut = uicontrol('Style', 'pushbutton', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 0.05, 0.15, but_height], ...
        'String', 'Next timepoint');
    controls.prevbut = uicontrol('Style', 'pushbutton', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.05, 0.05, 0.15, but_height], ...
        'String', 'Previous timepoint');
    controls.hshowchk = uicontrol('Style', 'checkbox', 'Parent', controls.hfig, ...
        'Units', 'normalized', ... 
        'Position', [0.8, 1 - 0.05 - 5 * but_height, 0.15, but_height], ...
        'String', 'Display edges');
    controls.hradiogroup = uibuttongroup('Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - (5 + 3) * but_height, 0.15, 3 * but_height], ...
        'Title', 'Z plane relative to top of tissue');
    controls.hfrm = uipanel('Parent', controls.hfig, ...
        'Units', 'normalized', ... 
        'Position', [0.05, 0.55 - 1.5 * but_height, 0.15, 3 * but_height], ...
        'Title', 'Edges stored for this timepoint');
    controls.hzradios = [];
    controls.hffchecks = [];
    radio_height = 0.8 / length(in.z_offsets);
    chk_height = radio_height/3;
    edge_string = {'Left bassal', 'Right basal', 'Midline'};
    for zoind = 1:length(in.z_offsets)+1
        if zoind ~= 1
            hdum = uicontrol('Style', 'radio', 'Parent', controls.hradiogroup, ...
                'Units', 'normalized', ...
                'Position', [0.4, 0.9 - (zoind - 1) * radio_height, 0.2, radio_height], ...
                'String', [num2str(in.z_offsets(zoind - 1)) ' um'], ...
                'HorizontalAlignment', 'center');
            controls.hzradios = [controls.hzradios; hdum];
        end
        chk_width = 0.8 / 4;
        hffcheck_row = zeros(3, 1);
        for eind = 1:4
            if (eind == 1) && (zoind > 1)
                hfchklbl = uicontrol('Style', 'text', 'Parent', controls.hfrm, ...
                    'Units', 'normalized', ...
                    'Position', [0.5 - 1.5 * chk_width + (eind - 2) * chk_width, ...
                                0.5 + length(in.z_offsets)/2 * chk_height - (zoind-1.75) * chk_height, ...
                                chk_width, chk_height],...
                'String', [num2str(in.z_offsets(zoind - 1)) ' um'], ...
                'HorizontalAlignment', 'right');
            elseif (zoind == 1) && (eind > 1)
                hzchlbl = uicontrol('Style', 'text', 'Parent', controls.hfrm, ...
                    'Units', 'normalized', ...
                    'Position', [0.5 - 1.5 * chk_width + (eind - 1.5) * chk_width, ...
                                0.5 + length(in.z_offsets)/2 * chk_height - (zoind-1.75) * chk_height, ...
                                chk_width, chk_height],...
                'String', edge_string{eind - 1}, ...
                'HorizontalAlignment', 'center');
            elseif (zoind > 1) && (eind > 1)
                hffcheck_row(eind) = uicontrol('Style', 'checkbox', 'Parent', controls.hfrm, ...
                    'Units', 'normalized', ...
                    'Position', [0.5 - 1.5 * chk_width + (eind - 1) * chk_width, ...
                                0.5 + length(in.z_offsets)/2 * chk_height - (zoind-2) * chk_height, ...
                                chk_width, chk_height],...
                    'String', '', ...
                    'Enable', 'off');
                controls.hffchecks = [controls.hffchecks; hffcheck_row];
            end
        end
    end
end