function krox_20_base_script()

    %% Function to process krox20 data for tissue morphology
    curr_dir = fileparts(mfilename('fullpath'));
    addpath(genpath([curr_dir filesep '..']));
    
    %% Parameters
    z_offsets = [35, 40, 45];

    %% Choose base folder
    folder = uigetdir([], ...
        'Choose a folder containing a timecourse of CZI files...');

    if (folder == 0) 
        return;
    end
    
    %% Choose output file
    out_file = uiputfile('.xls', ...
        'Choose a location and filename to save the output to', ...
        [folder filesep 'ncad krox stack output.xls']);
    
    if (out_file == 0)
        return;
    end
    
    %% Loop over timepoints
    files = dir([folder filesep '*.czi']);

    in.filename = files(1).name;
    in.z_offsets = z_offsets;
    displayCzi(in);
%     for ind = 1:length(files)
% 
% 
% 
%     end

end


function out = displayCzi(in)

    but_height = 0.1;
    hfig = figure('Units', 'normalized', 'NumberTitle', 'off', ...
        'Name', in.filename);
    set(hfig, 'Position', [0 0 1 0.95]);
    hax = axes('Position', [0.25, 0.15, 0.5, 1-0.05-0.15]);
    hzlbl = uicontrol('Style', 'text', 'Parent', hfig, ...
        'Units', 'normalized', ...
        'Position', [0.2, 0.1, 0.05, 0.025], ...
        'HorizontalAlignment', 'right', ...
        'String', 'Z plane:');
    hzsl = uicontrol('Style', 'slider', 'Parent', hfig, ...
        'Units', 'normalized', ...
        'Position', [0.25, 0.1, 0.5, 0.025]);
    hclbl = uicontrol('Style', 'text', 'Parent', hfig, ...
        'Units', 'normalized', ...
        'Position', [0.2, 0.05, 0.05, 0.025], ...
        'HorizontalAlignment', 'right', ...
        'String', 'Channel:');
	hcsl = uicontrol('Style', 'slider', 'Parent', hfig, ...
        'Units', 'normalized', ...
        'Position', [0.25, 0.05, 0.5, 0.025]);
    hsettopbut = uicontrol('Style', 'pushbutton', 'Parent', hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - but_height, 0.15, but_height], ...
        'String', 'Set current Z plane as top of tissue');
    hledgebut = uicontrol('Style', 'pushbutton', 'Parent', hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - 2 * but_height, 0.15, but_height], ...
        'String', 'Take current edge as left basal surface');
    hredgebut = uicontrol('Style', 'pushbutton', 'Parent', hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - 3 * but_height, 0.15, but_height], ...
        'String', 'Take current edge as right basal surface');
    hmidlbut = uicontrol('Style', 'pushbutton', 'Parent', hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - 4 * but_height, 0.15, but_height], ...
        'String', 'Take current edge as midline');
    hnextbut = uicontrol('Style', 'pushbutton', 'Parent', hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 0.05, 0.15, but_height], ...
        'String', 'Next timepoint');
    hprevbut = uicontrol('Style', 'pushbutton', 'Parent', hfig, ...
        'Units', 'normalized', ...
        'Position', [0.05, 0.05, 0.15, but_height], ...
        'String', 'Previous timepoint');
    hshowchk = uicontrol('Style', 'checkbox', 'Parent', hfig, ...
        'Units', 'normalized', ... 
        'Position', [0.8, 1 - 0.05 - 5 * but_height, 0.15, but_height], ...
        'String', 'Display edges');
    hradiogroup = uibuttongroup('Parent', hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - (5 + 3) * but_height, 0.15, 3 * but_height], ...
        'Title', 'Z plane relative to top of tissue');
    hfrm = uipanel('Parent', hfig, ...
        'Units', 'normalized', ... 
        'Position', [0.05, 0.55 - 1.5 * but_height, 0.15, 3 * but_height], ...
        'Title', 'Edges stored for this timepoint');
    hzradios = [];
    hffchecks = [];
    radio_height = 0.8 / length(in.z_offsets);
    chk_height = radio_height;
    for zoind = 1:length(in.z_offsets)
        hdum = uicontrol('Style', 'radio', 'Parent', hradiogroup, ...
            'Units', 'normalized', ...
            'Position', [0.4, 0.9 - zoind * radio_height, 0.2, radio_height], ...
            'String', [num2str(in.z_offsets(zoind)) ' um'], ...
            'HorizontalAlignment', 'center');
        hzradios = [hzradios; hdum];
        chk_width = 0.8 / 3;
        hffcheck_row = zeros(1, 3);
        for eind = 1:3
            hffcheck_row(eind) = uicontrol('Style', 'checkbox', 'Parent', hfrm, ...
                'Units', 'normalized', ...
                'Position', [0.5 - chk_width * eind/6, ...
                            0.5 - chk_height * zoind/6, ...
                            chk_width, chk_height],...
                'String', '', ...
                'Enable', 'off');
        end
        hffchecks = [hffchecks; hffcheck_row]
    end
    disp(hffchecks);
end