function controls = setup_ui(data)

    %% general controls
    but_height = 0.1;
    controls.hfig = figure('Units', 'normalized', 'NumberTitle', 'off', ...
        'Name', data.filename, ...
        'MenuBar', 'none', ...
        'ToolBar', 'figure');
    set(controls.hfig, 'Position', [0 0 1 0.95]);
    controls.hax = axes('Position', [0.25, 0.15, 0.5, 1-0.05-0.15]);
    controls.hzlbl = uicontrol('Style', 'text', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.2, 0.1, 0.05, 0.025], ...
        'HorizontalAlignment', 'right', ...
        'String', 'Z plane:');
    controls.hzsl = uicontrol('Style', 'slider', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.25, 0.1, 0.5, 0.025]);
    controls.hclbl = uicontrol('Style', 'text', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.2, 0.05, 0.05, 0.025], ...
        'HorizontalAlignment', 'right', ...
        'String', 'Channel:');
	controls.hcsl = uicontrol('Style', 'slider', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.25, 0.05, 0.5, 0.025]);
    controls.hsettopbut = uicontrol('Style', 'pushbutton', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - but_height, 0.15, but_height], ...
        'String', 'Set current Z plane as top of tissue');
    controls.hledgebut = uicontrol('Style', 'pushbutton', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - 2 * but_height, 0.15, but_height], ...
        'String', 'Use current edge as left basal surface', ...
        'Enable', 'off', ...
        'Tag', 'L');
    controls.hmidlbut = uicontrol('Style', 'pushbutton', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - 3 * but_height, 0.15, but_height], ...
        'String', 'Use current edge as midline', ...
        'Enable', 'off', ...
        'Tag', 'M');
    controls.hredgebut = uicontrol('Style', 'pushbutton', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - 4 * but_height, 0.15, but_height], ...
        'String', 'Use current edge as right basal surface', ...
        'Enable', 'off', ...
        'Tag', 'R');
    controls.hnextbut = uicontrol('Style', 'pushbutton', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 0.05, 0.15, but_height], ...
        'String', 'Next timepoint', ...
        'Enable', 'on');
    controls.hprevbut = uicontrol('Style', 'pushbutton', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.05, 0.05, 0.15, but_height], ...
        'String', 'Previous timepoint', ...
        'Enable', 'off');
    controls.hshowchk = uicontrol('Style', 'checkbox', 'Parent', controls.hfig, ...
        'Units', 'normalized', ... 
        'Position', [0.8, 1 - 0.05 - 5 * but_height, 0.15, but_height], ...
        'String', 'Display edges');
    controls.hhicontrast = uicontrol('Style', 'checkbox', 'Parent', controls.hfig, ...
        'Units', 'normalized', ... 
        'Position', [0.8 + 0.15/2, 1 - 0.05 - 5 * but_height, 0.15/2, but_height], ...
        'String', 'High contrast?');
    controls.hradiogroup = uibuttongroup('Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.8, 1 - 0.05 - (5 + 3) * but_height, 0.15, 3 * but_height], ...
        'Title', 'Z plane relative to top of tissue');
    controls.hfrm = uipanel('Parent', controls.hfig, ...
        'Units', 'normalized', ... 
        'Position', [0.025, 0.55 - 1.5 * but_height, 0.2, 3 * but_height], ...
        'Title', 'Edges stored for this timepoint');
    controls.hrh4but = uicontrol('Style', 'pushbutton', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.025, 1 - 0.05 - but_height, 0.15, but_height], ...
        'String', 'Define rhombomere 3 by current ROI', ...
        'Enable', 'off', ...
        'Tag', 'Rh4');
    controls.hrh6but = uicontrol('Style', 'pushbutton', 'Parent', controls.hfig, ...
        'Units', 'normalized', ...
        'Position', [0.025, 1 - 0.05 - 2 * but_height, 0.15, but_height], ...
        'String', 'Define rhombomere 5 by current ROI', ...
        'Enable', 'off', ...
        'Tag', 'Rh6');
    controls.hzradios = [];
    controls.hffchecks = [];
    radio_height = 0.8 / length(data.z_offsets);
    chk_height = radio_height/3;
    edge_string = {'L', 'R', 'M', 'Rh4', 'Rh6'};
    
    %% radio buttons for choosing z plane and checkboxes to show which 
    %  edges have already been found
    for zoind = 1:length(data.z_offsets)+1
        if zoind ~= 1
            hdum = uicontrol('Style', 'radio', 'Parent', controls.hradiogroup, ...
                'Units', 'normalized', ...
                'Position', [0.4, 0.9 - (zoind - 1) * radio_height, 0.2, radio_height], ...
                'String', [num2str(data.z_offsets(zoind - 1)) ' um'], ...
                'HorizontalAlignment', 'center', ...
                'Enable', 'off');
            controls.hzradios = [controls.hzradios; hdum];
        end
        chk_width = 0.8 / (length(edge_string) + 1);
        hffcheck_row = [];
        for eind = 1:(length(edge_string) + 1)
            if (eind == 1) && (zoind > 1)
                hfchklbl = uicontrol('Style', 'text', 'Parent', controls.hfrm, ...
                    'Units', 'normalized', ...
                    'Position', [0.5 - 2.5 * chk_width + (eind - 2) * chk_width, ...
                                0.5 + length(data.z_offsets)/2 * chk_height - (zoind-1.75) * chk_height, ...
                                chk_width + 0.1, chk_height],...
                'String', [num2str(data.z_offsets(zoind - 1)) ' um'], ...
                'HorizontalAlignment', 'right');
            elseif (zoind == 1) && (eind > 1)
                hzchlbl = uicontrol('Style', 'text', 'Parent', controls.hfrm, ...
                    'Units', 'normalized', ...
                    'Position', [0.5 - 2.5 * chk_width + (eind - 1.5) * chk_width, ...
                                0.5 + length(data.z_offsets)/2 * chk_height - (zoind-1.75) * chk_height, ...
                                chk_width, chk_height],...
                'String', edge_string{eind - 1}, ...
                'HorizontalAlignment', 'center');
            elseif (zoind > 1) && (eind > 1)
                hffcheck_row = [hffcheck_row ...
                    uicontrol('Style', 'checkbox', 'Parent', controls.hfrm, ...
                    'Units', 'normalized', ...
                    'Position', [0.5 - 2.5 * chk_width + (eind - 1) * chk_width, ...
                                0.5 + length(data.z_offsets)/2 * chk_height - (zoind-2) * chk_height, ...
                                chk_width, chk_height],...
                    'String', '', ...
                    'Enable', 'off')];
%                 controls.hffchecks = [controls.hffchecks; hffcheck_row];
            end
        end
        controls.hffchecks = [controls.hffchecks; hffcheck_row];
    end
    
    %% toolbar setup
    set(0, 'ShowHidden', 'on');
    hkids = get(controls.hfig, 'Children');
    tgs = get(hkids, 'Tag');
    htbbs = get(hkids(strcmp(tgs, 'FigureToolBar')), 'Children');
    tg = get(htbbs, 'Tag');
    deltgind = ~(strcmp(tg, 'Standard.SaveFigure') | ...
                strcmp(tg, 'Standard.PrintFigure') | ...
                strcmp(tg, 'Exploration.ZoomIn') | ...
                strcmp(tg, 'Exploration.ZoomOut') | ...
                strcmp(tg, 'Exploration.Pan') | ...
                strcmp(tg, 'Exploration.DataCursor'));
    delete(htbbs(deltgind));
        
end